language: php
php:
  - "5.4"
branches:
  only:
    - master
before_script:
  - php -v
  - phpunit --version
  - curl -sS https://getcomposer.org/installer | php
  - chmod +x composer.phar
  - php composer.phar install -o
notifications:
  email:
    - vinyvicente@gmail.com

